codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false

coverage:
  precision: 2
  range:
    - 70.0
    - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 80%
        threshold: 5%
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto

github_checks:
  annotations: true

ignore:
  - 'src/core/extension.ts'
  - 'src/media/**/*'
  - 'src/libs/feature/feature-webview-creator/**/*'
  - 'src/libs/feature/feature-webview-service/**/*'
  - 'src/libs/feature/feature-webview-factory/**/*'
