codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false

coverage:
  precision: 2
  range:
    - 70.0
    - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 80%
        threshold: 5%
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto

github_checks:
  annotations: true

ignore:
  - 'src/core/extension.ts'
  - 'src/media/**/*'
  - 'src/libs/feature/feature-webview-creator/**/*'
  - 'src/libs/feature/feature-webview-service/**/*'
  - 'src/libs/feature/feature-webview-factory/**/*'
  - 'src/libs/feature/feature-json-file-change-handler/**/*'
  - 'src/libs/feature/feature-configuration-wizard/**/*'
  - 'src/libs/http/http-deepl-client/**/*'
  - 'src/libs/feature/feature-translation-service/**/*'
  - 'src/libs/util/util-highlight-missing-values/**/*'
  - 'src/libs/feature/feature-active-text-editor-changed-handler/**/*'
  - 'src/libs/feature/feature-text-document-changed-handler/**/*'
  - 'src/libs/util/util-file-diff/**/*'
  - 'src/libs/module/module-translation/**/*'
  - 'src/libs/file-io/file-io-file-reader/**/*'
  - 'src/libs/file-io/file-io-file-writer/**/*'
  - 'src/libs/feature/feature-file-watcher-creator/**/*'
  - 'src/libs/store/store-file-location-store/**/*'
  - 'src/libs/feature/feature-empty-json-value-symbol-provider/**/*'
  - 'src/libs/feature/feature-file-change-handler-factory/**/*'
  - 'src/libs/module/module-base-action/**/*'
  - 'src/libs/feature/feature-i18next-scanner-service/**/*'
