version: "0.2"
ignorePaths:
  - package-lock.json
  - package.json
dictionaryDefinitions: []
dictionaries: []
words:
  - Dsonar
  - enduml
  - lngs
  - qvotaxon
  - startuml
ignoreWords: []
import: []
