name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      CODECOV_UPLOAD_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get VS Code Versions
        run: curl --output vscode-stable-versions.json https://update.code.visualstudio.com/api/releases/stable

      - name: Cache VS Code Versions
        uses: actions/cache@v4
        with:
          path: .vscode-test/
          key: ${{ runner.os }}-vscode-test-${{ hashFiles('**/src/*.ts', 'vscode-stable-versions.json') }}
          restore-keys: |
            ${{ runner.os }}-vscode-test-

      - name: Install dependencies
        run: pnpm install

      - name: Lint & Test
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: pnpm run test:coverage

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Build
        run: pnpm run compile:sourcemaps
