name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache VS Code Versions
        id: cache-vscode
        uses: actions/cache@v4
        with:
          path: .vscode-test/
          key: ${{ runner.os }}-vscode-test-${{ hashFiles('**/src/*.ts', 'vscode-stable-versions.json') }}
          restore-keys: |
            ${{ runner.os }}-vscode-test-

      - name: Get VS Code Versions
        if: steps.cache-vscode.outputs.cache-hit != 'true'
        run: curl --output vscode-stable-versions.json https://update.code.visualstudio.com/api/releases/stable

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run compile

      #- name: Lint
      #  run: npm run lint

      - name: Lint & Test
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: npm run test:clover

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Pre-release extension
        if: matrix.os == 'ubuntu-latest'
        run: npx vsce package -o i18nWeave-vscode-${{ github.run_number }}.vsix --pre-release

      - name: Upload VSIX Artifact
        if: matrix.os == 'ubuntu-latest' # Only upload artifact on Ubuntu where release job runs
        uses: actions/upload-artifact@v4
        with:
          name: i18nWeave-vscode-${{ github.run_number }}-${{ matrix.os }}
          path: i18nWeave-vscode-${{ github.run_number }}.vsix
