name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache VS Code Versions
        id: cache-vscode
        uses: actions/cache@v4
        with:
          path: .vscode-test/
          key: ${{ runner.os }}-vscode-test-${{ hashFiles('**/src/*.ts', 'vscode-stable-versions.json') }}
          restore-keys: |
            ${{ runner.os }}-vscode-test-

      - name: Get VS Code Versions
        if: steps.cache-vscode.outputs.cache-hit != 'true'
        run: curl --output vscode-stable-versions.json https://update.code.visualstudio.com/api/releases/stable

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run compile

      #- name: Lint
      #  run: npm run lint

      - name: Lint & Test
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: npm run test:clover

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
