name: Pull Request

on: [pull_request]

permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine pnpm package cache path for os
        id: pnpm-cache-path
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            pnpm_cache_path="C:/pnpm/cache"
          else
            pnpm_cache_path="$HOME/.pnpm"
          fi
          echo "pnpm_cache_path=$pnpm_cache_path" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache pnpm packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-path.outputs.pnpm_cache_path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install # pnpm ci is not supported yet

      - name: Build
        run: pnpm run compile-tests

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
