name: Pull Request

on: [pull_request]

permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine npm package cache path for os
        id: npm-cache-path
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            npm_cache_path="C:/npm/cache"
          else
            npm_cache_path="$HOME/.npm"
          fi
          echo "npm_cache_path=$npm_cache_path" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-path.outputs.npm_cache_path }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/src/*.ts') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run compile

      - name: Lint
        run: npm run lint

      - name: Test
        #skip ubuntu-latest because of $DISPLAY
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'windows-latest' }}
        run: npm run test
