name: Release

on:
  workflow_run:
    workflows: ['Build & Test']
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_KEY }}
          release-type: node

      - name: Cache pnpm store
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      - name: Create Pre-release extension
        if: ${{ steps.release.outputs.release_created }}
        run: npx vsce package -o i18nWeave-vscode-${{ steps.release.outputs.tag_name }}.vsix --pre-release

      - name: Upload Release Artifact to GitHub
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} i18nWeave-vscode-${{ steps.release.outputs.tag_name }}.vsix

      - name: Publish VS Code Extension
        if: ${{ steps.release.outputs.release_created }}
        uses: HaaLeo/publish-vscode-extension@v1.6.2
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: true

      - name: Create Sentry release
        if: ${{ steps.release.outputs.release_created }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: i18nweave
          SENTRY_PROJECT: i18nweave-vscode-r3
        with:
          version: ${{ steps.release.outputs.tag_name }}

      - name: Attest Build Provenance
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/attest-build-provenance@v1.3.1
        with:
          subject-path: i18nWeave-vscode-${{ steps.release.outputs.tag_name }}.vsix

    #   - name: Generate SBOM
    #     if: ${{ steps.release.outputs.release_created }}
    #     uses: anchore/sbom-action@v0
    #     with:
    #       path: 'out'
    #       format: 'spdx-json'
    #       output-file: 'sbom.spdx.json'

    #   - name: Attest SBOM
    #     if: ${{ steps.release.outputs.release_created }}
    #     uses: actions/attest-sbom@v1
    #     with:
    #       subject-path: '${{ github.workspace }}/out'
    #       sbom-path: 'sbom.spdx.json'
